export const AUTH_ASYNC_START = 'AUTH_ASYNC_START';
export const AUTH_ASYNC_FAIL = 'AUTH_ASYNC_FAIL';
export const AUTH_TEXT_CHANGED = 'AUTH_TEXT_CHANGED';
export const AUTH_SIGNUP_DONE = 'AUTH_SIGNUP_DONE';
export const AUTH_LOGIN_DONE = 'AUTH_LOGIN_DONE';
export const AUTH_LOGOUT_DONE = 'AUTH_LOGOUT_DONE';
export const AUTH_STILL_LOGGED_IN = 'AUTH_STILL_LOGGED_IN';

export const HABIT_ASYNC_START = 'HABIT_ASYNC_START';
export const HABIT_GET_ALL_DONE = 'HABIT_GET_ALL_DONE';
export const HABIT_ADD_NEW_DONE = 'HABIT_ADD_NEW_DONE';
export const HABIT_SAVE_CHANGE_DONE = 'HABIT_SAVE_CHANGE_DONE';
export const HABIT_RECORD_DONE = 'HABIT_RECORD_DONE';
export const HABIT_RECORD_UNDO_DONE = 'HABIT_RECORD_UNDO_DONE';
export const HABIT_DELETE_DONE = 'HABIT_DELETE_DONE';
export const HABIT_ASYNC_FAIL = 'HABIT_ASYNC_FAIL';
export const HABIT_RECORD_TOGGLED = 'HABIT_RECORD_TOGGLED';

export const NAV_MENU_OPEN = 'NAV_MENU_OPEN';
export const NAV_MENU_CLOSE = 'NAV_MENU_CLOSE';
export const NAV_PROMPT_OPEN = 'NAV_LOGOUT_PROMPT_OPEN';
export const NAV_PROMPT_CLOSE = 'NAV_LOGOUT_PROMPT_CLOSE';