export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_TEXT_CHANGED = 'AUTH_TEXT_CHANGED';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const HABIT_GET_ALL_START = 'HABIT_GET_ALL_START';
export const HABIT_GET_ALL_DONE = 'HABIT_GET_ALL_DONE';
export const HABIT_ADD_NEW_START = 'HABIT_ADD_NEW_START';
export const HABIT_ADD_NEW_DONE = 'HABIT_ADD_NEW_DONE';
export const HABIT_SAVE_CHANGE_START = 'HABIT_SAVE_CHANGE_START';
export const HABIT_SAVE_CHANGE_DONE = 'HABIT_SAVE_CHANGE_DONE';
export const HABIT_RECORD = 'HABIT_RECORD';
export const HABIT_RECORD_UNDO = 'HABIT_RECORD_UNDO';
export const HABIT_DELETE_DONE = 'HABIT_DELETE_DONE';
export const HABIT_START_ASYNC = 'HABIT_START_ASYNC';

export const NAV_MENU_OPEN = 'NAV_MENU_OPEN';
export const NAV_MENU_CLOSE = 'NAV_MENU_CLOSE';
export const NAV_PROMPT_OPEN = 'NAV_LOGOUT_PROMPT_OPEN';
export const NAV_PROMPT_CLOSE = 'NAV_LOGOUT_PROMPT_CLOSE';