export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_TEXT_CHANGED = 'AUTH_TEXT_CHANGED';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const HABIT_GET_ALL_HABITS_START = 'HABIT_GET_ALL_HABITS_START';
export const HABIT_GET_ALL_HABITS = 'HABIT_GET_ALL_HABITS';

export const NAV_MENU_OPEN = 'NAV_MENU_OPEN';
export const NAV_MENU_CLOSE = 'NAV_MENU_CLOSE';
export const NAV_LOGOUT_PROMPT_OPEN = 'NAV_LOGOUT_PROMPT_OPEN';
export const NAV_LOGOUT_PROMPT_CLOSE = 'NAV_LOGOUT_PROMPT_CLOSE';